### ISSUE TITLE
Pros and Cons vs Calligraphy

### ISSUE THREAD

**Issue by Alexander--** [ppicas/custom-typeface#1]
Just wander, what are possible downsides of using [Callygraphy](https://github.com/chrisjenx/Calligraphy) to achive the same results? Have you investigated it before creating this library?

**Comment by ppicas** [comment]
Yeah, Callygraphy and CustomTypeface are pretty much the same. I didn't investigated too much before publishing this project. I had the idea and immediately I started the implementation. Later I discovered Callygraphy. I didn't published any library to Maven central repository before, so I thought that this was a good chance.

Comparing with Callygraphy this project use a simpler approach, so we could say that is easier to maintain. Also CustomTypeface provides an attribute (customTypefaceIgnoreParents) that will give you more control when you are defining styles with complex hierarchies.
